<?php
/**
 * @file
 * Code for the Napo Film feature.
 */

include_once 'napo_film.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function napo_film_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['film_main_video_teaser'] = array(
    'label' => t('Film Video teaser'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function napo_film_form_napo_video_node_form_alter(&$form, &$form_state) {
  // Show napo film field only for video type - napo film.
  $form['field_napo_film'] += array(
    '#states' => array(
      'visible' => array(
        'select[name^="field_video_type"]' => array('value' => 2727),
      ),
    ),
  );
}
