<?php
/**
 * @file
 * Code for the Napo Lesson feature.
 */

include_once 'napo_lesson.features.inc';

/**
 * Implements hook_menu().
 */
function napo_lesson_menu() {
  $items = array();
  $items['using-napo/napo-for-teachers/download_video/%'] = array(
    'title' => 'Download lesson video',
    'page callback' => 'napo_lesson_download_video',
    'page arguments' => array(3),
    'access callback' => TRUE,
  );
  // Reorder lesson tab for lessons, but it redirects
  // to it's lesson toolkit tab.
  $items['node/%/reorder_lessons_r'] = array(
    'title' => 'Reorder lessons',
    'page callback' => 'napo_lesson_reorder_lesson_redirect',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'napo_lesson_reoder_lessons_redirect_callback',
  );

  // Reorder toolkit tab.
  $items['taxonomy/term/%taxonomy_term/reorder_toolkit'] = array(
    'title' => 'Reorder toolkit',
    'page callback' => 'napo_lesson_reorder_toolkit',
    'page arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'napo_lesson_reorder_toolkit_access',
    'access arguments' => array(2),
    'weight' => 3,
  );
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function napo_lesson_menu_alter(&$items) {
  // Add access callback for Reorder lesson tab.
  $items['node/%/reorder_lessons']['access callback'] = 'napo_lesson_reoder_lessons_access_callback';
}

/**
 * Redirect the user to the Reorder lessons page of the toolkit.
 */
function napo_lesson_reorder_lesson_redirect($nid) {
  $toolkit_id = _napo_lesson_get_toolkit_id($nid);
  if (!empty($toolkit_id)) {
    drupal_goto('node/' . $toolkit_id . '/reorder_lessons');
  }
  else {
    drupal_goto();
  }
}

/**
 * Callback for lesson toolkit reorder local task.
 */
function napo_lesson_reorder_toolkit($term) {
  $view = views_get_view('lesson_toolkit_reorder');
  $view->set_display('reorder_toolkit');
  $view_filters = $view->display_handler->get_option('filters');
  $view_filters['field_target_ages_tid']['value'] = drupal_map_assoc(array($term->tid));
  $overrides = array();
  $overrides['filters'] = $view_filters;
  foreach ($overrides as $option => $definition) {
    $view->display_handler->override_option($option, $definition);
  }
  $view->pre_execute();
  return $view->render('reorder_toolkit');
}

/**
 * Access callback for Reorder toolkit tab.
 */
function napo_lesson_reorder_toolkit_access($term) {
  if (user_access('edit any lesson_toolkit content') && $term->vocabulary_machine_name == 'target_ages') {
    return TRUE;
  }
  return FALSE;
}

/**
 * Reorder tab on lessons only visible if have toolkit.
 */
function napo_lesson_reoder_lessons_redirect_callback() {
  if (!user_access('edit any lesson content')) {
    return FALSE;
  }
  // Reorder menu only for toolkit.
  $node = node_load(arg(1));
  if ($node && $node->type == 'lesson') {
    $toolkit = field_get_items('node', $node, 'field_lesson_toolkit');
    if (!empty($toolkit)) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Implements hook_module_implements_alter().
 */
function napo_lesson_module_implements_alter(&$implementations, $hook) {
  // Run our hook after the views hook.
  if ($hook == 'menu_alter') {
    if (isset($implementations['napo_lesson'])) {
      unset($implementations['napo_lesson']);
      $implementations['napo_lesson'] = FALSE;
    }
  }
}

/**
 * Access callback for Reorder lessons tab.
 */
function napo_lesson_reoder_lessons_access_callback($options) {
  // Run the default access callback.
  $access_callback = $options[0];
  $access_arguments = $options[1];
  $access = call_user_func_array($access_callback, $access_arguments);
  if (!$access) {
    return FALSE;
  }
  // Reorder menu only for films.
  $node = node_load(arg(1));
  if ($node && $node->type == 'lesson_toolkit') {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_theme().
 */
function napo_lesson_theme() {
  return array(
    'right_menu' => array(
      'variables' => array(
        'node' => array(),
      ),
      'template' => 'theme/right_menu',
    ),
    'top_menu' => array(
      'variables' => array(
        'node' => array(),
        'lessons' => array(),
      ),
      'template' => 'theme/top_menu',
    ),
    'napo_lesson_first_lesson_link' => array(
      'variables' => array('entity' => NULL, 'file' => NULL, 'delta' => NULL),
    ),
    'download_whole_lesson' => array(
      'variables' => array(
        'video_id' => array(),
      ),
      'template' => 'theme/download_whole_lesson',
    ),
  );
}

function napo_lesson_get_download_block($node) {
  global $language;
  $file_uri = $node->field_file[$language->language][0]['uri'];
  $lesson_video = $node->field_lesson_video[LANGUAGE_NONE][0]['entity'];
  $video = $lesson_video->field_video;
  $video_uri = @$video['en'][0]['uri'];
  if (!empty($video[$language->language])) {
    $video_uri = $video[$language->language][0]['uri'];
  }
  $video_id = $lesson_video->nid;
  $resources_required = $node->field_resources_required[LANGUAGE_NONE];

  if ($video_uri) {
    $output = '<a href="' . url('using-napo/napo-for-teachers/download_video/' . $video_id) . '">';
    $output .= t('Video');
    $size = @filesize($video_uri);
    if ($size) {
      $output .= ' <span class="related_size">(' . format_size($size) . ')</span>';
    }
    $output .= '</a>';
    $items[] = $output;
  }

  if ($file_uri) {
    $output = '<a href="' . file_create_url($file_uri) . '">';
    $output .= t('Lesson');
    $size = @filesize($file_uri);
    if ($size) {
      $output .= ' <span class="related_size">(' . format_size($size) . ')</span>';
    }
    $output .= '</a>';

    $items[] = $output;
  }

  if ($node->type == 'lesson') {
    $items[] = l(t('Teacher guidance'),'node/' . $node->nid . '/guidance');
  }
  else {
    $items[] = l(t('Facilitator guidance'),'node/' . $node->nid . '/guidance');
  }

  if ($resources_required) {
    $items[] = l(t('Related resources'),'node/' . $node->nid . '/related_resources');
  }

  $items[] = '<a href="' . url('node/' . $node->nid . '/download_all') . '">' . t('DOWNLOAD ALL') . '</a>';
  $list = theme('item_list', array('items' => $items));
  return '<div class="download--section--block"><h3>' . t('Download') . '</h3>' . $list . '</div>';
}

/**
 * Implements hook_preprocess_node().
 */
function napo_lesson_preprocess_node(&$vars) {
  $node = $vars['node'];

  if($node->type == 'msds_activities') {
    if (!empty($vars['preprocess_fields'])) {
      if (in_array('download_block', $vars['preprocess_fields'])) {
        $vars['download_block'] = napo_lesson_get_download_block($node);
      }
    }
  }

  if($node->type == 'lesson') {
    if (!empty($vars['preprocess_fields'])) {
      // Right Menu.
      if (in_array('right_menu', $vars['preprocess_fields'])) {
        drupal_add_js(drupal_get_path('module', 'napo_lesson') . '/js/right_menu.js');
        $vars['right_menu'] = theme('right_menu', array());
      }
      // Top Menu
      if (in_array('top_menu', $vars['preprocess_fields'])) {
        drupal_add_js(drupal_get_path('module', 'napo_lesson') . '/js/top_menu.js');
        $lessons = views_get_view_result('lessons', 'block_1');
        $vars['top_menu'] = theme('top_menu', array(
          'node' => $node,
          'lessons' => $lessons,
        ));
      }

      if (in_array('download_block', $vars['preprocess_fields'])) {
        $vars['download_block'] = napo_lesson_get_download_block($node);
      }

      // Download whole lesson.
      if (in_array('download_whole_lesson', $vars['preprocess_fields'])
       && !empty($vars['field_lesson_video'][0]['target_id'])) {
        $vars['download_whole_lesson'] = theme('download_whole_lesson', array(
          'video_id' => $vars['field_lesson_video'][0]['target_id'],
        ));
      }
      if (in_array('toolkit_title', $vars['preprocess_fields'])) {
        $toolkit = node_load(_napo_lesson_get_toolkit_id($node->nid));
        if (!empty($toolkit)) {
          $title = field_get_items('node', $toolkit, 'title_field');
          $title = current($title)['safe_value'];
          $title = array(
            '#markup' => '<h2 class="napo-lesson-toolkit-title">' . $title . '</h2>',
            '#weight' => 0,
          );
          $vars['toolkit_title'] = drupal_render($title);
        }
      }
      if (in_array('lessons_note', $vars['preprocess_fields'])) {
        $note = variable_get('napo_lesson_note_text', '');
        $vars['lessons_note'] = t($note);
      }
    }
  }
}

/**
 * Implements hook_js_alter().
 *
 * Remove accordion from content
 */
function napo_lesson_js_alter(&$javascript) {
  if(arg(0) == 'node') {
    $node = node_load(arg(1));
    if($node && $node->type == 'lesson') {
      unset($javascript[drupal_get_path('module', 'wysiwyg_accordion').'/js/wysiwyg_accordion.js']);
    }
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function napo_lesson_field_formatter_info() {
  $info = array(
    'first_lesson_link' => array(
      'label' => t('First Lesson Link'),
      'field types' => array('text'),
      'description' => t('Get the link of the first lesson in the lesson kit'),
    ),
  );
  return $info;
}

/**
 * Implements hook_field_formatter_view().
 */
function napo_lesson_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'first_lesson_link':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#theme' => 'napo_lesson_first_lesson_link',
          '#entity' => $entity,
          '#file' => $item,
          '#delta' => $delta,
        );
      }
      break;
  }
  return $element;
}

/*
* Formats multilanguage file for download
*/
function theme_napo_lesson_first_lesson_link($element) {
  $entity = $element['entity'];
  $lesson = views_get_view_result('lessons', 'block_2', $entity->nid);

  $output = l($entity->title, 'node/'.$lesson[0]->nid);
  return $output;
}

/**
 * Callback for Download whole lesson button.
 */
function napo_lesson_download_video($nid) {
  global $language;
  $node = node_load($nid);
  if (!empty($node)) {
    $wrapper = entity_metadata_wrapper('node', $node);
    $file = $wrapper->language($language->language)->field_video->value();
    if (!empty($file)) {
      $file = current($file);
      $headers = array(
        'Content-Type'              => $file['filemime'],
        'Content-Disposition'       => 'attachment; filename="' . drupal_basename($file['uri']) . '"',
        'Content-Length'            => $file['filesize'],
        'Content-Transfer-Encoding' => 'binary',
        'Pragma'                    => 'no-cache',
        'Cache-Control'             => 'must-revalidate, post-check=0, pre-check=0',
        'Expires'                   => '0',
        'Accept-Ranges'             => 'bytes',
      );
      file_transfer($file['uri'], $headers);
    }
  }
  drupal_set_message(t("There was an error downloading the lesson's video!"), 'error');
  drupal_not_found();
}

/**
 * Function to get the toolkit id based on a lesson id.
 */
function _napo_lesson_get_toolkit_id($nid) {
  $toolkit_id = 0;
  $node = node_load($nid);
  $toolkit = field_get_items('node', $node, 'field_lesson_toolkit');
  if (!empty($toolkit)) {
    $toolkit_id = $toolkit[0]['target_id'];
  }
  return $toolkit_id;
}
