<?php
/**
 * @file
 * Code for the Napo Lesson feature.
 */

include_once 'napo_lesson.features.inc';

/**
 * Implements hook_theme().
 */
function napo_lesson_theme() {
  return array(
    'right_menu' => array(
      'variables' => array(
        'node' => array(),
      ),
      'template' => 'theme/right_menu',
    ),
    'top_menu' => array(
      'variables' => array(
        'node' => array(),
        'lessons' => array(),
      ),
      'template' => 'theme/top_menu',
    ),
  );
}

/**
 * Implements hook_preprocess_node().
 */
function napo_lesson_preprocess_node(&$vars) {
  $node = $vars['node'];

  if($node->type == 'lesson') {
    if (!empty($vars['preprocess_fields'])) {
      // Right Menu
      if (in_array('right_menu', $vars['preprocess_fields'])) {
        drupal_add_js(drupal_get_path('module', 'napo_lesson') . '/js/right_menu.js');
        $vars['right_menu'] = theme('right_menu', array());
      }
      // Top Menu
      if (in_array('top_menu', $vars['preprocess_fields'])) {
        drupal_add_js(drupal_get_path('module', 'napo_lesson') . '/js/top_menu.js');
        $lessons = views_get_view_result('lessons', 'block_1');
        $vars['top_menu'] = theme('top_menu', array(
          'node' => $node,
          'lessons' => $lessons,
        ));
      }
    }
  }
}

/**
 * Implements hook_js_alter().
 *
 * Remove accordion from content
 */
function napo_lesson_js_alter(&$javascript) {
  if(arg(0) == 'node') {
    $node = node_load(arg(1));
    if($node && $node->type == 'lesson') {
      unset($javascript[drupal_get_path('module', 'wysiwyg_accordion').'/js/wysiwyg_accordion.js']);
    }
  }
}
