<?php

/**
 * NRV-112 Activities - Resources required accordion missing.
 */
function napo_msd_update_7001() {
  module_enable(['views_autocomplete_filters']);
  features_revert_module('napo_lesson');
  features_revert_module('napo_msd');
}

/**
 * NRV-150 MSDs Activity: conversation starter behaviour.
 */
function napo_msd_update_7002() {
  features_revert(array('napo_msd' => array('views_view')));
}
