<?php

/**
 * Implments hook_form_FORM_ID_alter().
 */
function napo_common_form_chosen_admin_settings_alter(&$form, $form_state) {
  // Add options to chosen 30.
  $form['chosen_minimum_single']['#options']['30'] = '30';
  $form['chosen_minimum_multiple']['#options']['30'] = '30';
}

/**
 * Implements hook_node_submit().
 */
function napo_common_node_submit($node, $form, &$form_state) {
  // Add default alias for translations as the english alias (if one exists).
  $entity_trans_form = !empty($form_state['entity_translation']);
  if ($entity_trans_form && $form_state['entity_translation']['is_translation'] === TRUE
    && empty($form_state['values']['path']['alias'])) {
    $path = path_load(array('source' => 'node/' . $node->nid, 'language' => 'en'));
    if (!empty($path)) {
      $node->path['alias'] = $path['alias'];
    }
  }
}

/**
 * Implements hook_file_update().
 */
function napo_common_file_update($file) {
  // Move gallery files to gallery.
  if (!empty($file->field_is_gallery[LANGUAGE_NONE][0]['value'])
    && strpos($file->uri, 'public://gallery') !== 0
    && strpos($file->uri, 'public://migrated-images') !== 0) {
    $file = file_move($file, 'public://gallery', FILE_EXISTS_RENAME);
  }
}
