<?php
/**
 * @file
 * Code for the osh_image_gallery feature.
 */

include_once 'osh_image_gallery.features.inc';


/**
 * Implements hook_menu_alter().
 */
function osh_image_gallery_menu_alter(&$items) {
  // Change callback to use our function.
  $items['admin/content/file']['page callback'] = 'osh_image_gallery_admin_page_callback';
  // Unset the thumbnail MENU_LOCAL_ACTION from File page.
  unset($items['admin/content/file/thumbnails']);
}

/**
 * Callback for admin File page.
 */
function osh_image_gallery_admin_page_callback() {
  // Render our custom view for files.
  return views_embed_view('media_browser_osha');
}
