<?php

/**
 * Implements hook_requirements().
 */
function napo_migration_requirements($phase) {
  global $databases;
  if (!isset($databases['osha'])) {
    drupal_set_message('You must set in settings.php a connection to OSHA database for taxonomy import', 'warning');
  }
}
/**
 * Implements hook_migrate_api().
 */
function napo_migration_migrate_api() {
  $osha_taxonomies_common_arguments = array(
    'source_connection' => 'osha',
    'source_version' => 7,
    'group_name' => 'osha_taxonomies',
    'class_name' => 'NapoMultilingualDrupalTerm7Migration',
  );
  $data_export_path = napo_migration_get_data_dir();
  $api = array(
    'api' => 2,
    'groups' => array(
      'osha_taxonomies' => array(
        'title' => t('Import taxonomies from OSHA'),
      ),
      'napo_content' => array(
        'title' => t('Import content from NAPO export'),
      ),
      'napo_files' => array(
        'title' => t('Import files from NAPO export'),
      ),
    ),
    'migrations' => array(
      'Thesaurus' => array(
        'source_vocabulary' => 'thesaurus',
        'destination_vocabulary' => 'thesaurus',
        'class_name' => 'NapoMultilingualDrupalTerm7Migration',
        'description' => 'Import Thesaurus Taxonomy from OSHA',
      ) + $osha_taxonomies_common_arguments,
      'NaceCodes' => array(
        'source_vocabulary' => 'nace_codes',
        'destination_vocabulary' => 'nace_codes',
        'class_name' => 'NapoMultilingualDrupalTerm7Migration',
        'description' => 'Import Nace Codes Taxonomy from OSHA',
      ) + $osha_taxonomies_common_arguments,
      'Pages' => array(
        'class_name' => 'NapoMigrationPages',
        'description' => 'Import Napo Pages',
        'group_name' => 'napo_content',
        'file_name' => $data_export_path . '/napo_pages.csv',
        'file_name_whitelist' => $data_export_path . '/napo_pages_whitelist.json',
      ),
      'Files' => array(
        'class_name' => 'NapoMigrateFiles',
        'description' => 'Import Napo Pages',
        'group_name' => 'napo_files',
        'file_name' => $data_export_path . '/napo_files.txt',
        'file_name_whitelist' => $data_export_path . '/napo_files_whitelist.json',
      ),
    ),
  );
  return $api;
}

function napo_migration_get_data_dir($subdirectory = '') {
  $ret = variable_get('napo_data_dir', NULL);
  if (empty($ret)) {
    drupal_set_message('Please configure the "osha_data_dir" variable to point to your data storage', 'error');
  }
  else {
    if (!empty($subdirectory)) {
      $ret .= DIRECTORY_SEPARATOR . $subdirectory;
    }
  }
  return $ret;
}
