<?php
/**
 * @file
 * Code for the Napo Gallery feature.
 */

include_once 'napo_gallery.features.inc';

/**
 * Implements hook_preprocess_node().
 */
function napo_gallery_preprocess_node(&$vars) {
  $node = $vars['node'];
  if ($node->type == 'napo_album') {
    $params = drupal_get_query_parameters();
    if (isset($params['page'])) {
      hide($vars['content']['field_image']);
    }
  }
}


/**
 * Implements hook_form_alter().
 */
function napo_gallery_form_napo_album_node_form_alter(&$form, &$form_state, $form_id) {
  // Limit the title field of the album to 50 chars.
  $lang = element_children($form['title_field'])[0];
  $form['title_field'][$lang][0]['value']['#maxlength'] = 50;
}
