<?php
/**
 * @file
 * Code for the Napo search feature.
 */

include_once 'napo_search.features.inc';


/**
 * Implements hook_search_api_solr_query_alter().
 */
function napo_search_search_api_solr_query_alter(array &$call_args, SearchApiQueryInterface $query) {
  // Replace % with * to handle requested widlcard % (non-existing in solr).
  if (!empty($call_args['query'])) {
    $call_args['query'] = str_replace('%', '*', $call_args['query']);
  }
}

/**
 * Implements hook_form_alter().
 */
function napo_search_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    // Overwrite the search page default url.
    // Unset the form elements - the search view needs just the search param.
    $form['#action'] = url('search');
    $form['#method'] = 'get';
    unset($form['form_token']);
    unset($form['#submit']);
    unset($form['form_build_id']);
    unset($form['form_id']);
  }

  /*
   * SITUATION: Search forms with facet filters and keywords search.
   * PROBLEM: When searching for a keyword after using a facet filter, the
   * facet filter is ignored by Views.
   * SOLUTION: Add facet filters as hidden form fields to Views exposed forms.
   */

  // Check if this form is a Search API form. This could be replaced with the
  // value of a custom Views setting like ie. "Include facets".
  if (isset($form_state['view']) && $form_state['view']->base_table === 'search_api_index_default_multilingual_node_index') {
    // Get quary parameters.
    $query_parameters = drupal_get_query_parameters();

    // If any facet query parameters are provided.
    if (!empty($query_parameters['f'])) {
      // Iterate through facet query parameters.
      foreach ($query_parameters['f'] as $key => $value) {
        // Add hidden form field for facet parameter.
        $form['f[' . $key . ']'] = array(
          '#type' => 'hidden',
          '#value' => $value,
          '#weight' => -1,
        );
      }
    }
  }
}

/**
 * Implements hook_form_views_exposed_form_alter().
 */
function napo_search_form_views_exposed_form_alter(&$form, &$form_state) {
  // Set default language current language.
  if (!empty($form['search_api_language'])) {
    global $language;
    if ($language->language != LANGUAGE_NONE) {
      $form['search_api_language']['#default_value'] = $language->language;
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function napo_search_views_pre_render(&$view) {
  if ($view->name == 'search' && $view->current_display == 'page'){
    // Overwrite view title.
    if (!empty($view->exposed_data['search_block_form'])) {
      $view->build_info['title'] = t('Search results for @search_word',
        array('@search_word' => '"' . $view->exposed_data['search_block_form'] . '"'));
    }
    else {
      $view->build_info['title'] = t('Search results');
    }
  }
}

/**
 * Implements hook_node_view().
 */
function napo_search_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'search_results') {
    drupal_add_js(drupal_get_path('module', 'napo_search') . '/js/search_results.js');
    if ($node->type == 'napo_video' && !empty($node->content['node_link'][0]['#markup'])) {
      $span = '<span class="glyphicon glyphicon-play-circle view-film-details-icon" title="' . t('View detail') . '"></span>';
      $node->content['node_link'][0]['#markup'] = l($span, 'node/' . $node->nid, array('html' => TRUE));
    }
  }
}

/**
 * Implements hook_node_view_alter().
 */
function napo_search_node_view_alter(&$build) {
  if ($build['#view_mode'] == 'search_results') {
    //Highlight the searched text.
    $view = views_get_current_view();
    if ($view) {
      foreach ($view->result as $result) {
        if ($result->entity->nid != $build['#node']->nid) {
          continue;
        }
        $body = $result->_entity_properties['search_api_excerpt'];
        if ($body) {
          $build['body'][0]['#markup'] = $body;
        }
        break;
      }
    }
  }
}